# Generated by Django 5.2.14 on 2026-05-27 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_ingestionbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPRawRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_row_data', models.JSONField()),
                ('row_number', models.IntegerField()),
                ('normalization_status', models.CharField(choices=[('PENDING', 'PENDING'), ('NORMALIZED', 'NORMALIZED'), ('FAILED', 'FAILED'), ('REVIEW_REQUIRED', 'REVIEW_REQUIRED')], default='PENDING', max_length=30)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_raw_records', to='emissions.company')),
                ('ingestion_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_raw_records', to='emissions.ingestionbatch')),
            ],
            options={
                'db_table': 'sap_raw_records',
                'ordering': ['row_number'],
            },
        ),
    ]
