# Generated by Django 5.2.14 on 2026-05-28 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_emissionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityRawRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_row_data', models.JSONField()),
                ('row_number', models.IntegerField()),
                ('normalization_status', models.CharField(default='PENDING', max_length=50)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.company')),
                ('ingestion_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.ingestionbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
