# Generated by Django 5.2.14 on 2026-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_utilityrawrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='source_record',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='source_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
