# Generated by Django 5.2.14 on 2026-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0007_travelrawrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='audit_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
